model:
  _target_: get_model.model.model.GETNucleotideMotifAdaptorV3
  cfg:
    motif_scanner:
      num_motif: 637
      include_reverse_complement: true
      bidirectional_except_ctcf: true
      motif_prior: true
      learnable: false
      has_bias: true
    loss:
      components:
        motif:
          _target_: torch.nn.MSELoss
          reduction: "mean"
      weights:
        motif: 1
    metrics:
      components:
        motif: ["pearson", "spearman", "r2"]
