defaults:
  - base_config
  - model/GETFinetuneATAC@_here_
  - dataset/atac_expression@dataset
  - machine/manitou_hvl2108
  - _self_


task:
  layer_names: []
  test_mode: "perturb"
  gene_list: 
    - "PPIF"
  # mutations: null
  mutations: "/burg/pmg/users/xf2217/get_revision/PPIF/prepared_data.tsv"


# task:
#   layer_names: []
#   test_mode: "perturb"
#   gene_list:
#     - "PPIF"
#   mutations: 

assembly: "hg38"


training:
  save_ckpt_freq: 1
  epochs: 100
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false

optimizer:
  lr: 0.00005
  min_lr: 0.0001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.95]

wandb:
  project_name: "chrombpnet"
  run_name: "thp1"

finetune:
  checkpoint: null
  model_prefix: "model."
  patterns_to_freeze: []
