defaults:
  - base_region_config
  - model/GETRegionPretrain@_here_
  - machine/pc_region_v2
  - _self_

assembly: "hg38"

dataset:
    root: ${machine.data_path}
    metadata_path: 'data/cell_type_pretrain_human_bingren_shendure_apr2023_test.txt'
    num_region_per_sample: 200
    transform: null
    data_type: 'fetal_adult'
    leave_out_celltypes: ""
    leave_out_chromosomes: ""
    quantitative_atac: true
    sampling_step: 100
    mask_ratio: 0.5

training:
  save_ckpt_freq: 1
  epochs: 1600
  warmup_epochs: 40
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false

optimizer:
  lr: 0.00015
  min_lr: 0.00001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.95]

run:
  project_name: "GETRegionPretrain"
  run_name: "debug"

finetune:
  resume_ckpt: null


eval_tss: false
