defaults:
  - base_region_zarr_config
  - model/GETRegionFinetuneHiCOE@_here_
  - machine/pc
  - finetune/v1_finetune@finetune
  - dataset/h1esc_hic_oe@dataset
  - _self_

assembly: "hg38"

task:
  layer_names: []
  test_mode: "interpret"

training:
  save_ckpt_freq: 1
  epochs: 100
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false

dataset:
  quantitative_atac: true
  sampling_step: 100
  mask_ratio: 0

optimizer:
  lr: 0.0001
  min_lr: 0.000001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.999]

run:
  project_name: "H1ESC_HIC_OE"
  run_name: "debug"

finetune:
  pretrain_checkpoint: false
  strict: false
  use_lora: false
  layers_with_lora: []
  checkpoint: null
  patterns_to_freeze: []
  model_key: 'model'

  #   - checkpoint: GETRegionFinetune_k562_abc/k6tj3d9k/checkpoints/best.ckpt
  #     model_key: 'state_dict'
  #     strict: false
  #     rename_config:
  #       model.: abc.contact_map.

eval_tss: true
log_image: false
