defaults:
  - base_region_zarr_config
  - model/GETRegionFinetuneHiC@_here_
  - finetune/lightning@finetune
  - machine/pc_hic
  - _self_

assembly: "hg38"

dataset:
    zarr_path: /home/xf2217/Projects/4dn_h1esc/peak_motif/original/H1ESC.4dn_h1esc.4dn_h1esc.peak_motif.zarr
    celltypes: H1ESC.4dn_h1esc.4dn_h1esc
    num_region_per_sample: 400
    transform: null
    leave_out_celltypes: null
    leave_out_chromosomes: 'chr11'
    quantitative_atac: true
    sampling_step: 100
    mask_ratio: 0.0
    hic_path: /home/xf2217/Projects/geneformer_nat/data/H1_ESC.hic
    hic_resolution: 5000
    hic_method: "observed" # or observed
    hic_normalization: "KR"

training:
  save_ckpt_freq: 1
  epochs: 1000
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false
  add_lr_monitor: true

optimizer:
  lr: 0.00015
  min_lr: 0.00001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.95]

run:
  project_name: "h1esc_hic_region_zarr"
  run_name: "cnnk3_observe_lr0.00015_cosine"

task:
  layer_names: ['region_embed']
  test_mode: "interpret"
  gene_list: 'MYC,SOX10,SOX2,RET'


finetune:
  # resume_ckpt: /home/xf2217/output/h1esc_hic_region_zarr/debug_oe/checkpoints/last-v5.ckpt
  pretrain_checkpoint: false
  use_lora: false
  checkpoint: null #/home/xf2217/output/h1esc_hic_region_zarr/debug_oe/checkpoints/last-v5.ckpt
  patterns_to_freeze: []
  rename_config:
    "model.": ""
    "hic_header": "head_hic"

eval_tss: false
log_image: true

hydra:
  job:
    name: ${run.project_name}_${run.run_name}
  run:
    dir: ${machine.output_dir}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
