defaults:
  - base_region_zarr_config
  - model/GETRegionFinetuneHiCV2@_here_
  - finetune/lightning@finetune
  - machine/pc_hic
  - _self_

assembly: "hg38"

dataset:
    zarr_path: ${machine.data_path}/H1_ESC_ATAC_Seq_biological_replicates.4dn_h1esc.4DNESLMCRW2C.max.peak_motif.zarr
    celltypes: H1_ESC_ATAC_Seq_biological_replicates.4dn_h1esc.4DNESLMCRW2C.max
    num_region_per_sample: 400
    transform: null
    leave_out_celltypes: null
    leave_out_chromosomes: 'chr10,chr11'
    quantitative_atac: true
    normalize: true
    sampling_step: 100
    mask_ratio: 0.0
    hic_path: ${machine.data_path}/H1_ESC.hic
    hic_resolution: 5000
    hic_method: "oe" # or observed
    hic_normalization: "NONE"

training:
  save_ckpt_freq: 1
  epochs: 1000
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false
  add_lr_monitor: true

optimizer:
  lr: 0.00015
  min_lr: 0.00001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.95]

run:
  project_name: "h1esc_hic_region_zarr_adapt"
  run_name: "from_scratch_oe"

task:
  layer_names: ['region_embed']
  test_mode: "interpret"
  gene_list: 'MYC,SOX10,SOX2,RET'


finetune:
  resume_ckpt: null #/home/xf2217/output/h1esc_hic_region_zarr_adapt/no_lora_normalize_oe/checkpoints/best.ckpt
  pretrain_checkpoint: false
  use_lora: false
  checkpoint: null #/home/xf2217/output/h1esc_hic_region_zarr/debug_oe/checkpoints/last-v5.ckpt
  # layers_with_lora: ['region_embed']
  patterns_to_freeze: []
  rename_config:
    "model.": ""
    "hic_header": "head_hic"

eval_tss: false
log_image: true

hydra:
  job:
    name: ${run.project_name}_${run.run_name}
  run:
    dir: ${machine.output_dir}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
