defaults:
  - base_nucleotide_motif_adaptor_config
  - model/GETNucleotideMotifAdaptorV3@_here_
  - finetune/v1_finetune@finetune
  - machine/pc_adaptor
  - _self_

assembly: "hg38"

dataset:
    sequence_zarr: ${machine.data_path}/hg38.zarr
    motif_zarr: ${machine.data_path}/hg38_motif.zarr
    transform: null
    sequence_length: 512
    leave_out_chromosomes: 'chr11'


training:
  save_ckpt_freq: 1
  epochs: 100
  warmup_epochs: 0
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: true

optimizer:
  lr: 0.0001
  min_lr: 0.0001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.999]

run:
  project_name: "GETNucleotideMotifAdaptorV3"
  run_name: "debug"
  use_wandb: true


finetune:
  pretrain_checkpoint: false
  strict: true
  use_lora: false
  checkpoint: null
  patterns_to_freeze: []

eval_tss: true
log_image: true
